name: Alan Blackman
favicon: null
layout_spectrum: 0.8886631708592176
typography_spectrum: 0.646331567550078
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3314864190761
  lightness: 0.7970883841626346
  saturation: 0.32395014935173094
  rhythmicContrast: 0.9312713851686567
purpose: []
